### ISSUE TITLE
Self hosting the server

### ISSUE THREAD

**Issue by ln-12** [twofas/2fas-server#2]
Hey, first of all: 2FAS is an awesome app and I really like using it!

Do you plan to support self hosting the server software? Well, technically this is already possible using this repo but I do not see any way to change the server URL in the apps and browser extension. Is this a planned feature?

**Comment by 2fas-com** [comment]
The app itself doesn't require any server. We're using external server only for additional features like BE and in-app notifications. Tbh we don't have plans for this to be a feature. At least for now.

**Comment by teambvd** [comment]
This somewhat defeats the purpose of the app IMO - if I can't have control over all aspects of my data with 2FAS, then there's limited reason to use it over the various other options out there... I hope this feature can be reconsidered.

**Comment by ibaraki-douji** [comment]
Hey, if you guys are still intrested of deploying your own 2FAS servers i can post a tutorial / steps to set it up on your server since i just did it on mine. Tho if you want to go and change the server be ready to also change the Android/IOS app and the browser extension code as well (to change the API url in both softwares)

@CeeBeeEh to awnser your question, no you will not loose them, the API is here to add icons on the fly, sync your phone with the browser extension, manage notifications, and system reports when there is an error on the phone app. The API will not and will never keep the token in the server.
(for Authy they also keep the token on their server for their backup thing)

**Comment by turbotorsten** [comment]
> Hey, if you guys are still intrested of deploying your own 2FAS servers i can post a tutorial / steps to set it up on your server since i just did it on mine. Tho if you want to go and change the server be ready to also change the Android/IOS app and the browser extension code as well (to change the API url in both softwares)
> 
> @CeeBeeEh to awnser your question, no you will not loose them, the API is here to add icons on the fly, sync your phone with the browser extension, manage notifications, and system reports when there is an error on the phone app. The API will not and will never keep the token in the server. (for Authy they also keep the token on their server for their backup thing)

I was also looking into self hosting this, but there seems no way to change the server url in the app / extension. Does that require recompiling both?

**Comment by turbotorsten** [comment]
> @turbotorsten yes you need to recompile the extension (just need to change some envs) for the app it's also simple, edit the url inside the code (2 places) and recompile to an APK for the server side it's way more complicated as it require you to bypass some s3 storage, change the url, and others minors elements
> 
> also here is the docs i made : https://wiki.ibaraki.app/en/docker/2fas You can also check my repos (github/gitlab) to see all the changes i made

Thank you for the fast reply, I'll look into it once I find the time 😄
